# Generated by Django 5.1.15 on 2026-07-22 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_add_style_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='QARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], default='major', max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QAScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_scores', to='documents.documentjob')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='qa.qarule')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('job', 'rule')},
            },
        ),
    ]
