# Generated by Django 5.1.15 on 2026-07-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarule',
            name='auto_approve_threshold',
            field=models.FloatField(default=0.8, help_text='Score threshold for auto-approval (0.0-1.0)'),
        ),
    ]
