# Generated by Django 5.1.15 on 2026-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='rate_limit',
            field=models.IntegerField(default=100, help_text='Requests per hour'),
        ),
    ]
