# Generated by Django 5.1.15 on 2026-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentjob',
            name='style_mode',
            field=models.CharField(choices=[('faithful', 'Faithful'), ('fluid', 'Fluid'), ('creative', 'Creative'), ('formal', 'Formal'), ('casual', 'Casual')], default='fluid', max_length=20),
        ),
    ]
