# Generated by Django 5.1.15 on 2026-07-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_style_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentjob',
            name='bilingual',
            field=models.BooleanField(default=False),
        ),
    ]
