# Generated by Django 5.1.15 on 2026-07-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_lang', models.CharField(default='en', max_length=10)),
                ('target_lang', models.CharField(default='hi', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glossaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
                ('target', models.CharField(max_length=500)),
                ('context', models.TextField(blank=True, help_text='Optional context for when to use this term')),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred translation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='glossaries.glossary')),
            ],
            options={
                'ordering': ['source'],
                'unique_together': {('glossary', 'source')},
            },
        ),
    ]
