# Generated by Django 5.1.15 on 2026-07-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='batch_uploads/'),
        ),
    ]
