# Generated by Django 5.1.15 on 2026-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_user_id_ac289d_idx',
            old_name='audit_user_action_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_created_2c1626_idx',
            old_name='audit_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_resourc_2a3aef_idx',
            old_name='audit_resource_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('translate', 'Translate'), ('export', 'Export'), ('import', 'Import'), ('share', 'Share')], max_length=20),
        ),
    ]
